name: CI

on:
  push:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  # 
  # ----------------------------------------------------------------------------------------------
  # Using local .git directory
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch 
  # ----------------------------------------------------------------------------------------------
  job2:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Sync Changed Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: Trigger Sync Jobs
        run: |
          pokemonFilePaths=[]

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *"Pokemon"* ]]; then
              pokemonFilePaths+="geek-stash/trading-card-games/main/$file"
            fi
          
          echo $pokemonFilePaths.toString()

          CODE=`curl --write-out '%{http_code}' \
            --silent \
            --request POST \
            --header 'content-type: application/json' \
            --url '${{ secrets.POKEMON_SYNC_ENDPOINT }}' \
            --data [[ toJSON($pokemonFilePaths) ]]`
          
          echo $CODE

          done
