name: Manual Sync

on: 
  workflow_dispatch:
    inputs:
      series-directory:   
        required: true
      set-name:
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.series-directory }}"
        echo "Tags: ${{ github.event.inputs.set-name }}" 