name: Manual Sync

on: 
  workflow_dispatch:
    inputs:
      series-directory:   
        required: true
      set-name:
        required: true
      upload-images:
        type: boolean
        required: true

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
         files: pokemon/sets/${{ github.event.inputs.series-directory }}/${{ github.event.inputs.set-name }}
         token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: |
          mainDir="geek-stash/trading-card-games/main"
          setDir="pokemon/sets/${{ github.event.inputs.series-directory }}/${{ github.event.inputs.set-name }}"
          imageDir="$setDir/images"
          
          filePaths+='"'$mainDir'/'$setDir'/${{ github.event.inputs.set-name }}.json",'

          if [[ ${{ github.event.inputs.upload-images }} ]]; then
            cd "$imageDir"
            
            for filename in ./*; do
              filePaths+='"'$mainDir'/'$imageDir'/'${filename:2}'",'
            done
          fi

          filePaths=[${filePaths::-1}]
          
          CODE=`curl --write-out '%{http_code}' \
            --silent \
            --request POST \
            --header 'content-type: application/json' \
            --url '${{ secrets.POKEMON_SYNC_ENDPOINT }}' \
            --data ${filePaths}`
            
          echo $CODE